### ISSUE TITLE
Does not respond to dragging

### ISSUE THREAD

**Issue by lolmaus** [lifeart/ember-click-outside-modifier#1]
Hey comrade!

We have two controls:

* a picture container where a picture can be positioned by dragging
* a text field

When either control is focused, a relevant toolbar appears. I've used `ember-click-outside-modifier` to hide toolbars, and it's working fine.

But the following won't work:
* focus the text field, see the text toolbar appear;
* start dragging the picture.

As a result, both toolbars are visible.

I think this is because dragging does not produce the click event.

Will you accept a PR allowing it?

PS I've seen *"If you need more control on click outside - take a look at ember-click-outside"* in the readme. Is it because you haven't had time/need to add more functionality? Or do you deliberately want to keep this modifier non-configurable?

**Comment by lifeart** [comment]
Hi Andrey! Thank you for issue, I think behavour relates to https://github.com/lifeart/ember-click-outside-modifier/blob/master/addon/modifiers/click-outside.js#L7

My goal not competite with ember-click-outside in functionality and be modifier-only addon.
I think it's possible to add more control using event names to capture.

Like

```hbs
<div {{click-outside this.onClickOutside (array "click" "touchstart")}} />
```

**Comment by lolmaus** [comment]
Sounds like a plan!

I'll submit a PR if my team decide we need the drag behavior fixed.

**Comment by lifeart** [comment]
@lolmaus `ember-click-outside-modifier@2.0.0` should include ability to specify event name to capture, thank to @alexlafroscia!

Closing issue as implemented.
