### ISSUE TITLE
Convert to v2 addon

### ISSUE THREAD

**Issue by SergeAstapov** [lifeart/ember-click-outside-modifier#12]
As this addon provides only run-time functionality hence it's the great candidate for v2 addon conversion.
There is guide great [Porting an Addon to V2](https://github.com/embroider-build/embroider/blob/main/PORTING-ADDONS-TO-V2.md) guide I suggest we follow.

My thought process of the next steps is to have PRs in the following order:

1. [x] convert to monorepo https://github.com/lifeart/ember-click-outside-modifier/pull/13
1. [x] convert addon to v2 https://github.com/lifeart/ember-click-outside-modifier/pull/14
1. [x] prepare for `ember-modifier` v4 per [migration guide](https://github.com/ember-modifier/ember-modifier/blob/master/MIGRATIONS.md) https://github.com/lifeart/ember-click-outside-modifier/pull/19
1. [x] release new major v4.0.0

@lifeart do you have any thoughts, concerns? I can volunteer to work on those

**Comment by SergeAstapov** [comment]
@lifeart I think this addon is ready for v4.0.0 to go out

**Comment by lifeart** [comment]
@SergeAstapov thank you for your work, trying to release it from my PC
![image](https://user-images.githubusercontent.com/1360552/162400590-fec34d29-9a35-4c4b-94d0-83afce521490.png)

**Comment by SergeAstapov** [comment]
@lifeart thank you for publishing!

@lifeart that error is weird indeed. I wonder if Node.js version had messed up things (just a random thought).
Also, wonder if missing `GITHUB_AUTH` env variable per [Release Process](https://github.com/lifeart/ember-click-outside-modifier/blob/master/RELEASE.md) was a culprit.

Anyway I've created #20 to track that issue separately so we can close this one out now!

**Comment by lifeart** [comment]
Looks like release-it for windows has incorrect binary configuration..
