### ISSUE TITLE
Events triggered before the modifier was created

### ISSUE THREAD

**Issue by simonihmig** [lifeart/ember-click-outside-modifier#6]
Hey, I tried your addon with a simple modal use case:
* you click on a button
* that sets a tracked property `show` to true
* this will render the modal, which uses the modifier on its own element

Expected result:
Modal is shown

Actual result:
Modal is immediately hidden again. 

I could see in the debugger that the button click was captured by the modifier's event listener. And as it is on the button, it is clearly outside the modal's element, the modal is hidden again.

Based on what I vaguely remember on how Ember's runloop works, I would have expected that the action that is called by `{{on "click"}}` (the button click) would be executed in the "actions" phase, i.e. in a later tick/microtask, so that the actual event already finished bubbling up the DOM. But maybe that's not the case (anymore)...

Maybe the event listeners need to be attached in a `later()` call?

Reproduction: #7

**Comment by lifeart** [comment]
Interesting, https://github.com/lifeart/ember-click-outside-modifier/issues/1 may be related here

**Comment by lifeart** [comment]
@simonihmig thank you for reporting and amazing test case!

`ember-click-outside-modifier@2.0.1` published

**Comment by simonihmig** [comment]
> I expect any tracked modification will schedule rerender using "setTimeout" (or it may be true only for GlimmerJS itself), did not expect we have rerender in same runloop with event.

Yeah, that was exactly what puzzled me.

> Also, I'm not clear why we have event on new DOM node in same runloop.

AFAIU, the dom node the modifier is attached to does not really matter, as the modifier creates the event listener on the root `document`, right? So when the order is:
1. click event on button
2. modifier is invoked (in *same* event loop)
3. event listener is added to document
4. event bubbles up to document
5. event triggers modifier's listener
 
Then this this would explain it, right?

But again, given my (naive) understanding of the runloop, I would have expected this to happen:
1. click event on button
2. event bubbles up to document
3. new event loop / runloop phase
4. modifier is invoked
5. event listener is added to document
6. the past event is already "gone", so no trigger

> ember-click-outside-modifier@2.0.1 published

Nice, thanks for the super quick turnaround time! :)

**Comment by lifeart** [comment]
> But again, given my (naive) understanding of the runloop, I would have expected this to happen: ...

Yes! Same for me..

Glad to help to get it solved!
